NoPermission: '&6[NULL] &fДля использования этой команды вам нужно &6приобрести&f ее в магазине'
NoArgs: '&6[NULL] &fУкажите один аргумент из списка в &6/vehicles&f!'
GroundError: '&6[NULL] &fВам нужно &6стоять на земле&f что бы призвать транспорт!'
OnlyOne: '&6[NULL] &fУ вас уже есть транспорт'
Spawned: '&6[NULL] &fВы заспавнили &6{0}&f!'
VehicleList: '&6[NULL] &fСписок всего транспорта доступного для покупки: &6{0}'
Vehicles:
  - 'horse'
  - 'donkey'
  - 'llama'

TamedAnimals:
  - 'horse'
  - 'donkey'
  - 'llama'